# Generated by Django 4.0 on 2023-12-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_alter_myuser_groups_alter_myuser_user_permissions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
