# Generated by Django 4.0 on 2023-12-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0005_alter_myuser_options_remove_myuser_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='role_user',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='state',
        ),
    ]
