# Generated by Django 4.0 on 2023-12-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0007_myuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_boss',
            field=models.BooleanField(default=False),
        ),
    ]
