# Generated by Django 4.0 on 2023-12-21 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='typeletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='mainletter.typeletter'),
        ),
    ]
