# Generated by Django 4.0 on 2023-12-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainletter', '0002_alter_template_typeletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='name',
            new_name='title',
        ),
    ]
