# Generated by Django 4.0 on 2023-12-25 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
        ('mainletter', '0003_rename_name_template_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accountapp.myuser'),
            preserve_default=False,
        ),
    ]
