# Generated by Django 4.0 on 2023-12-12 04:37

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountapp', '0008_myuser_is_boss'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LetterReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('letter_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zarik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_name', models.CharField(max_length=300)),
                ('adress', models.CharField(max_length=300)),
                ('street', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=50)),
                ('inn_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('soato', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LetterSummons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('letter_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=150)),
                ('report_name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('litter_number', models.CharField(max_length=15, unique=True)),
                ('inn_number', models.CharField(max_length=15)),
                ('stir_number', models.PositiveBigIntegerField(default=0)),
                ('phone_number', models.CharField(max_length=13)),
                ('report_date', models.DateTimeField()),
                ('created_date_add', models.DateTimeField(default=datetime.datetime(2023, 12, 17, 4, 37, 17, 973895, tzinfo=utc))),
                ('state', models.BooleanField(choices=[(True, 'Topshirdi'), (False, 'Topshirmadi')], default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountapp.myuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LetterInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=150)),
                ('adress', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('litter_number', models.CharField(max_length=15)),
                ('inn_number', models.CharField(max_length=15)),
                ('stir_number', models.PositiveBigIntegerField(default=0)),
                ('phone_number', models.CharField(max_length=13)),
                ('soato', models.CharField(max_length=50)),
                ('report_date', models.DateTimeField(auto_now=True)),
                ('created_date_add', models.DateTimeField(default=datetime.datetime(2024, 1, 11, 4, 37, 17, 973453, tzinfo=utc))),
                ('state', models.BooleanField(choices=[(True, 'Topshirdi'), (False, 'Topshirmadi')], default=False)),
                ('letter_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='letterapp.lettercategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountapp.myuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LetterCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('letter_name', models.CharField(max_length=50)),
                ('litter_number', models.CharField(max_length=15, unique=True)),
                ('company_name', models.CharField(max_length=150)),
                ('ptsh', models.CharField(max_length=15)),
                ('stir_number', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('report_name', models.CharField(max_length=100)),
                ('report_date', models.DateTimeField()),
                ('company_own', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountapp.myuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
