# Generated by Django 4.2.6 on 2023-11-21 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettersummons',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 12, 50, 11, 453800, tzinfo=datetime.timezone.utc)),
        ),
    ]
