# Generated by Django 4.2.6 on 2023-11-19 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letterapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="letterinstruction",
            name="inn_number",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="letterinstruction",
            name="created_date_add",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 19, 12, 30, 0, 268202, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="lettersummons",
            name="created_date_add",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 24, 12, 30, 0, 269084, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
