# Generated by Django 4.0 on 2023-12-12 05:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 5, 15, 48, 939994, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lettersummons',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 5, 15, 48, 940444, tzinfo=utc)),
        ),
    ]
