# Generated by Django 4.2.6 on 2023-11-21 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0002_alter_lettersummons_created_date_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 12, 51, 0, 517343, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lettersummons',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 12, 51, 0, 517748, tzinfo=datetime.timezone.utc)),
        ),
    ]
