# Generated by Django 4.2.6 on 2023-11-19 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letterapp", "0002_letterinstruction_inn_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letterinstruction",
            name="created_date_add",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 19, 12, 59, 6, 763028, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="letterinstruction",
            name="report_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="lettersummons",
            name="created_date_add",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 24, 12, 59, 6, 763981, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
