# Generated by Django 4.0 on 2023-12-21 06:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0002_alter_letterinstruction_created_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 20, 6, 40, 1, 358155, tzinfo=utc)),
        ),
    ]
