# Generated by Django 4.2.6 on 2023-11-19 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letterapp", "0003_alter_letterinstruction_created_date_add_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letterinstruction",
            name="created_date_add",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 19, 13, 14, 28, 841700, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="letterinstruction",
            name="litter_number",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="lettersummons",
            name="created_date_add",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 24, 13, 14, 28, 842485, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
