# Generated by Django 4.0 on 2023-12-12 05:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0003_alter_letterinstruction_created_date_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 5, 22, 26, 685306, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lettersummons',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 5, 22, 26, 685756, tzinfo=utc)),
        ),
    ]
