# Generated by Django 4.0 on 2023-12-25 05:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0003_alter_letterinstruction_created_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 5, 55, 4, 868090, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='letterinstruction',
            name='user',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
