# Generated by Django 4.2.6 on 2023-11-20 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("letterapp", "0002_alter_letterinstruction_created_date_add_and_more"),
        ("letterapp", "0004_alter_letterinstruction_created_date_add_and_more"),
    ]

    operations = []
