# Generated by Django 4.2.6 on 2023-11-28 05:02

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0004_lettersummons_inn_number_lettersummons_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zarik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_name', models.CharField(max_length=150)),
                ('adress', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('inn_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 28, 5, 2, 54, 259388, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lettersummons',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 5, 2, 54, 259787, tzinfo=datetime.timezone.utc)),
        ),
    ]
