# Generated by Django 4.0 on 2023-12-12 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0004_alter_letterinstruction_created_date_add_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LetterCategory',
            new_name='ReportCategory',
        ),
        migrations.RenameField(
            model_name='letterinstruction',
            old_name='report_name',
            new_name='letter_name',
        ),
        migrations.RenameField(
            model_name='letterinstruction',
            old_name='letter_category',
            new_name='report_category',
        ),
        migrations.AlterField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 9, 9, 11, 636589, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lettersummons',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 9, 9, 11, 637048, tzinfo=utc)),
        ),
    ]
