# Generated by Django 4.2.6 on 2023-11-20 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letterapp", "0005_merge_20231120_0342"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letterinstruction",
            name="created_date_add",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 20, 3, 42, 13, 898034, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="lettersummons",
            name="created_date_add",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 25, 3, 42, 13, 898827, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
