# Generated by Django 4.0 on 2023-12-25 10:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0005_alter_letterinstruction_created_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 10, 21, 11, 217915, tzinfo=utc)),
        ),
    ]
