# Generated by Django 4.0 on 2023-12-12 09:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0005_rename_lettercategory_reportcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 9, 10, 17, 484468, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='letterinstruction',
            name='report_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='letterinstructuion', to='letterapp.reportcategory'),
        ),
        migrations.AlterField(
            model_name='lettersummons',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 9, 10, 17, 484911, tzinfo=utc)),
        ),
    ]
