# Generated by Django 4.2.6 on 2023-11-28 10:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0006_alter_letterinstruction_created_date_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zarik',
            name='soato',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 28, 10, 38, 6, 247954, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lettersummons',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 10, 38, 6, 248378, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='zarik',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
