# Generated by Django 4.0 on 2023-12-27 11:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainletter', '0004_template_user'),
        ('letterapp', '0007_rename_createtemplate_letterinstruction_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterinstruction',
            name='typeletter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainletter.typeletter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 11, 55, 2, 484028, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='letterinstruction',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
