# Generated by Django 4.0 on 2023-12-01 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0007_zarik_soato_alter_letterinstruction_created_date_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterinstruction',
            name='soato',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 31, 12, 42, 22, 977821, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lettersummons',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 12, 42, 22, 978288, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='zarik',
            name='adress',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='zarik',
            name='company_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='zarik',
            name='inn_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='zarik',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='zarik',
            name='soato',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='zarik',
            name='street',
            field=models.CharField(max_length=300),
        ),
    ]
