# Generated by Django 4.0 on 2023-12-27 13:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainletter', '0004_template_user'),
        ('letterapp', '0010_alter_letterinstruction_created_date_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 13, 8, 41, 257187, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='letterinstruction',
            name='typeletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letterinstructuion_typeletter', to='mainletter.typeletter'),
        ),
    ]
