# Generated by Django 4.0 on 2023-12-28 05:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0011_alter_letterinstruction_created_date_add_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letterinstruction',
            name='typeletter',
        ),
        migrations.AlterField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 27, 5, 42, 1, 773413, tzinfo=utc)),
        ),
    ]
