# Generated by Django 4.0 on 2023-12-28 05:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0012_remove_letterinstruction_typeletter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 27, 5, 45, 27, 230879, tzinfo=utc)),
        ),
    ]
