# Generated by Django 4.0 on 2023-12-28 05:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0013_alter_letterinstruction_created_date_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letterinstruction',
            name='letter_name',
        ),
        migrations.RemoveField(
            model_name='letterinstruction',
            name='user',
        ),
        migrations.AlterField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 27, 5, 49, 4, 824753, tzinfo=utc)),
        ),
    ]
