# Generated by Django 4.0 on 2023-12-28 05:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0014_remove_letterinstruction_letter_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letterinstruction',
            name='litter_number',
        ),
        migrations.AlterField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 27, 5, 50, 9, 789794, tzinfo=utc)),
        ),
    ]
