# Generated by Django 4.0 on 2023-12-28 06:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0016_rename_stir_number_letterinstruction_letter_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 27, 6, 54, 46, 516612, tzinfo=utc)),
        ),
    ]
