# Generated by Django 4.0 on 2023-12-28 07:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0017_alter_letterinstruction_created_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 27, 7, 24, 9, 267225, tzinfo=utc)),
        ),
    ]
