# Generated by Django 4.0 on 2024-01-08 05:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0022_alter_letterinstruction_created_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 5, 23, 52, 659869, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='PdfLetterInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdf_file', models.FileField(upload_to='pdfletterinstruction/unsigned/')),
                ('letterinstruction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='letterapp.letterinstruction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
