# Generated by Django 4.0 on 2024-01-08 05:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0023_alter_letterinstruction_created_date_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterinstruction',
            name='pdf_file',
            field=models.FileField(default=1, upload_to='pdfletterinstruction/unsigned/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 5, 52, 3, 205300, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='PdfLetterInstruction',
        ),
    ]
