# Generated by Django 4.0 on 2024-01-08 10:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0025_alter_letterinstruction_created_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 10, 12, 6, 525216, tzinfo=utc)),
        ),
    ]
