# Generated by Django 4.0 on 2023-12-12 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LetterInsturcionNoSigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.CharField(max_length=30)),
                ('letter', models.TextField()),
                ('report_name', models.CharField(max_length=150)),
                ('letter_name', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
