# Generated by Django 4.0 on 2023-12-15 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('letterinstructionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinyNoSigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='LetterInsturcionNoSigned',
        ),
    ]
