# Generated by Django 4.0 on 2023-12-15 07:02

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('letterinstructionapp', '0002_tinynosigned_delete_letterinsturcionnosigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinynosigned',
            name='new_desc',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tinynosigned',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
