# Generated by Django 4.0 on 2023-12-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterinstructionapp', '0003_tinynosigned_new_desc_tinynosigned_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinynosigned',
            name='new_desc',
            field=models.TextField(),
        ),
    ]
