# Generated by Django 4.2 on 2024-03-04 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lettersummonapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lettersummons",
            name="created_date_add",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 9, 12, 10, 40, 774748, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
