# Generated by Django 4.2 on 2024-03-04 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lettersummonapp", "0002_alter_lettersummons_created_date_add"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lettersummons",
            name="created_date_add",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 9, 12, 16, 55, 508842, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
