# Generated by Django 4.2 on 2024-03-25 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lettersummonapp", "0002_alter_lettersummons_created_date_add"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lettersummons",
            name="created_date_add",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 30, 6, 3, 7, 295577, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
